version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
    
defaults: &defaults
    docker:
      - image: fomiller/megatainer:latest
    environment:
      TF_VAR_username: "${SECRET_USERNAME^^}"
  
jobs:
  aws login:
    <<: *defaults
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          profile-name: default
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform init and validate:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: terragrunt run-all validate
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform plan:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: terragrunt run-all plan
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform apply:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: terragrunt run-all apply --terragrunt-non-interactive
          
workflows:
  version: 2
  Terraform Deploy:
    jobs:
      - aws login:
          context:
            - aws-credentials
            - dev-secrets
      - terraform init and validate:
          context:
            - aws-credentials
            - dev-secrets
          requires:
            - aws login
      - terraform plan:
          context:
            - aws-credentials
            - dev-secrets
          requires:
            - terraform init and validate
      - terraform apply:
          context:
            - aws-credentials
            - dev-secrets
          requires:
            - terraform plan
