version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  terragrunt:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
          profile-name: default
      - run:
          working_directory: us-east-1/dev/
          command: |
            terragrunt run-all validate
            terragrunt run-all plan
            terragrunt run-all apply --terragrunt-non-interactive
          
workflows:
  version: 2
  Terraform Deploy:
    jobs:
      - terragrunt:
          context:
            - aws-credentials
