version: 2.1
orbs:
  aws-terragrunt: smarshorbs/aws-terragrunt@2.2.0
jobs:
  terraform:
    executor: aws-terragrunt/default
    steps:
      - aws-terragrunt/set-up:
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
          aws-region: "us-east-1"
          tf-version: "1.3.6"
      - run: cd ./us-east-1/dev/
      - run: terragrunt run-all validate
      - run: terragrunt run-all plan
      - run: terragrunt run-all apply --terragrunt-non-interactive
        
        
workflows:
  terraform:
    jobs:
      - terraform:
          context:
            - aws-credentials
