version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  terragrunt:
    docker:
      - image: fomiller/megatainer:latest
    steps:
      - aws-cli/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID_DEV 
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY_DEV
      - checkout
      - run:
          working_directory: us-east-1/dev/
          command: |
            env
            terragrunt run-all validate
            terragrunt run-all plan
            terragrunt run-all apply --terragrunt-non-interactive
          
workflows:
  version: 2
  Terraform Deploy:
    jobs:
      - terragrunt:
          context:
            - aws-credentials
